#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include "stm32f1xx_hal.h"

#define APP_UART_BAUDRATE              115200U
#define APP_RADIO_DEFAULT_BAUDRATE     9600U
#define APP_RADIO_E28_UART_BAUD_BITS   5U
#define APP_RADIO_E28_AIR_RATE_BITS    0U
#define APP_RADIO_E28_CHANNEL          0x18U
#define APP_RADIO_E28_OPTION           0x04U
#define APP_RADIO_E28_LINK_ADDRESS     0x0001U
#define APP_UART_POLL_TIMEOUT_MS       10U
#define APP_UART_SELF_TEST_ECHO        0U
#define APP_UART_STARTUP_BANNER        1U
#define APP_UART_SOURCE_TAG_ENABLE     0U
#define APP_UART2_SOURCE_TAG           "[DT]"
#define APP_UART3_SOURCE_TAG           "[RTK]"
#define APP_RADIO_ROLE_MASTER          1U
#define APP_RADIO_ROLE_SLAVE           2U
#ifndef APP_RADIO_DEVICE_ROLE
#define APP_RADIO_DEVICE_ROLE          APP_RADIO_ROLE_SLAVE
#endif
#ifndef APP_RADIO_LOCAL_ID
#define APP_RADIO_LOCAL_ID             2U
#endif
#ifndef APP_RADIO_REMOTE_ID
#define APP_RADIO_REMOTE_ID            1U
#endif
#ifndef APP_RADIO_NETWORK_ID
#define APP_RADIO_NETWORK_ID           "1234567890"
#endif
#define APP_SYS_LED_TOGGLE_MS          500U

#define APP_RADIO_CONFIG_ON_FIRST_BOOT 1U
#define APP_RADIO_CONFIG_MARKER_ADDR   0x0801FC00U
#if APP_RADIO_DEVICE_ROLE == APP_RADIO_ROLE_MASTER
#define APP_RADIO_CONFIG_MARKER_VALUE  0x5243464DU
#elif APP_RADIO_DEVICE_ROLE == APP_RADIO_ROLE_SLAVE
#define APP_RADIO_CONFIG_MARKER_VALUE  0x52434653U
#else
#error "APP_RADIO_DEVICE_ROLE must be APP_RADIO_ROLE_MASTER or APP_RADIO_ROLE_SLAVE."
#endif
#define APP_RADIO_CONFIG_FIRST_BOOT_FORWARD 1U
#define APP_RADIO_CONFIG_STARTUP_WAIT_MS 3000U
#define APP_RADIO_CONFIG_GUARD_WAIT_MS 1200U
#define APP_RADIO_CONFIG_CMD_WAIT_MS   600U
#define APP_RADIO_CONFIG_VIEW_WAIT_MS  2200U
#define APP_RADIO_CONFIG_VIEW_BUFFER   768U
#define APP_RADIO_MODE_SWITCH_WAIT_MS  1000U

#define APP_WATCHDOG_TIMEOUT_MS        2000U
#define APP_WATCHDOG_ENABLE            1U
#define APP_WATCHDOG_LSI_HZ            40000U
#define APP_WATCHDOG_PRESCALER         64U
#define APP_WATCHDOG_PR_BITS           0x04U
#define APP_WATCHDOG_RELOAD \
  (((APP_WATCHDOG_TIMEOUT_MS * (APP_WATCHDOG_LSI_HZ / 1000U)) / APP_WATCHDOG_PRESCALER) - 1U)

#define APP_TEST_HANG_AFTER_BOOT_MS    0U

#define APP_SYS_LED_ACTIVE_LEVEL       GPIO_PIN_RESET
#define APP_SYS_LED_INACTIVE_LEVEL     GPIO_PIN_SET

#endif
