#ifndef BOOT_CONFIG_H
#define BOOT_CONFIG_H

#include "main.h"

#define BOOTLOADER_FLASH_BASE        0x08000000UL
#define BOOTLOADER_FLASH_SIZE_BYTES  (16UL * 1024UL)
#define APPLICATION_FLASH_BASE       (BOOTLOADER_FLASH_BASE + BOOTLOADER_FLASH_SIZE_BYTES)
#define APPLICATION_FLASH_SIZE_BYTES (112UL * 1024UL)

#define SRAM_BASE_ADDR               0x20000000UL
#define SRAM_SIZE_BYTES              (20UL * 1024UL)

#define SYS_LED_ACTIVE_LEVEL         GPIO_PIN_RESET
#define SYS_LED_INACTIVE_LEVEL       GPIO_PIN_SET

#define BOOT_JUMP_DELAY_MS           200U

#endif
